version: "3.8"

services:
  db:
    container_name: db
    image: postgres:latest
    environment:
      - POSTGRES_DB=urlshortener
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
    networks:
      - appnet
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    networks:
      - appnet
    command: redis-server --save "" --appendonly no --maxclients 10000

networks:
  appnet:
    driver: bridge
volumes:
  pgdata: {}